package com.foss.aihub.models

data class AppSettings(
    var theme: String = "auto",
    var loadLastOpenedAI: Boolean = true,
    var multipleDefaultAi: Boolean = false,
    var defaultServiceName: String?,
    var defaultServiceNames: Set<String> = emptySet(),
    var serviceOrder: List<String> = emptyList(),
    var enabledServices: Set<String> = emptySet(),
    var favoriteServices: Set<String> = emptySet(),
    var maxKeepAlive: Int = 5,
    var enableZoom: Boolean = true,
    var desktopView: Boolean = false,
    var thirdPartyCookies: Boolean = false,
    var fontSizePercentage: Int = 100,
    var updateFrequencyDays: Int = 3,
    var blockAdsAndTrackers: Boolean = true,
    var checkForUpdate: Boolean = true,
    var isProxy: Boolean = false,
    var proxyType: String = "http",
    var proxyHost: String = "localhost",
    var proxyPort: String = "9050",
    var customCss: String = "",
    var customJs: String = "",
    var filterCategories: Set<String> = emptySet(),
    var filterPrices: Set<String> = emptySet(),
    var filterPrivacy: Set<String> = emptySet(),
    var filterLoginRequired: Boolean? = null,
    var enableNewServicesByDefault: Boolean = false,
    var preferredCategories: Set<String> = emptySet(),
    var preferredPrices: Set<String> = emptySet(),
    var preferredPrivacy: Set<String> = emptySet(),
    var preferredLoginRequired: Boolean? = null
)